# Generated by Django 6.0.3 on 2026-05-12 01:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_merge_20260509_2206"),
    ]

    operations = [
        migrations.CreateModel(
            name="Monster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.CharField(max_length=80)),
                ("element", models.CharField(max_length=20)),
                ("habitat", models.CharField(max_length=60)),
                ("personality", models.CharField(max_length=60)),
                ("color_palette", models.CharField(max_length=80)),
                ("flavor_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monsters",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "monster",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonsterImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("public_image_url", models.URLField(blank=True, null=True)),
                ("image_storage_path", models.TextField(blank=True)),
                ("provider", models.CharField(max_length=50)),
                ("provider_model", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "monster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="monsters.monster",
                    ),
                ),
            ],
            options={
                "db_table": "monster_image",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonsterImageGenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "generation_mode",
                    models.CharField(
                        choices=[("fake", "Fake"), ("real", "Real")], max_length=10
                    ),
                ),
                ("sanitized_prompt", models.TextField(blank=True)),
                ("prompt_version", models.CharField(blank=True, max_length=40)),
                ("prompt_hash", models.CharField(blank=True, max_length=64)),
                ("provider", models.CharField(max_length=50)),
                ("provider_model", models.CharField(max_length=100)),
                ("provider_request_id", models.CharField(blank=True, max_length=120)),
                ("should_email_when_done", models.BooleanField(default=False)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notification_error_code",
                    models.CharField(blank=True, max_length=100),
                ),
                ("notification_error_message", models.TextField(blank=True)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("safe_error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_job",
                        to="monsters.monsterimage",
                    ),
                ),
                (
                    "monster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="image_generation_jobs",
                        to="monsters.monster",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_generation_jobs",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "monster_image_generation_job",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="monster",
            index=models.Index(
                fields=["owner", "-created_at"], name="monster_owner_i_659d11_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monster",
            index=models.Index(
                fields=["owner", "display_name"], name="monster_owner_i_6e9bbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monster",
            index=models.Index(
                fields=["owner", "element"], name="monster_owner_i_45fb0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monsterimage",
            index=models.Index(
                fields=["monster", "-created_at"], name="monster_ima_monster_760fc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monsterimage",
            index=models.Index(
                fields=["provider", "provider_model"],
                name="monster_ima_provide_c09b42_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monsterimagegenerationjob",
            index=models.Index(
                fields=["owner", "-created_at"], name="monster_ima_owner_i_99780b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monsterimagegenerationjob",
            index=models.Index(
                fields=["owner", "status", "-created_at"],
                name="monster_ima_owner_i_0d8acc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monsterimagegenerationjob",
            index=models.Index(
                fields=["monster", "-created_at"], name="monster_ima_monster_ab5d9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monsterimagegenerationjob",
            index=models.Index(
                fields=["generation_mode", "status"],
                name="monster_ima_generat_90c726_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="monsterimagegenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "queued"),
                    models.Q(
                        ("started_at__isnull", False),
                        ("finished_at__isnull", False),
                        _connector="OR",
                    ),
                    _negated=True,
                ),
                name="job_queued_has_no_timestamps",
            ),
        ),
        migrations.AddConstraint(
            model_name="monsterimagegenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "running"),
                    models.Q(
                        ("started_at__isnull", True),
                        ("finished_at__isnull", False),
                        _connector="OR",
                    ),
                    _negated=True,
                ),
                name="job_running_has_started_at_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="monsterimagegenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "succeeded"),
                    models.Q(
                        ("started_at__isnull", True),
                        ("finished_at__isnull", True),
                        _connector="OR",
                    ),
                    _negated=True,
                ),
                name="job_succeeded_has_both_timestamps",
            ),
        ),
        migrations.AddConstraint(
            model_name="monsterimagegenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status", "failed"), ("status", "blocked"), _connector="OR"
                    ),
                    models.Q(
                        ("started_at__isnull", True),
                        ("finished_at__isnull", True),
                        _connector="OR",
                    ),
                    _negated=True,
                ),
                name="job_failed_blocked_have_both_timestamps",
            ),
        ),
        migrations.AddConstraint(
            model_name="monsterimagegenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("should_email_when_done", False),
                    models.Q(
                        models.Q(("notification_error_code", ""), _negated=True),
                        models.Q(("notification_error_message", ""), _negated=True),
                        _connector="OR",
                    ),
                    _negated=True,
                ),
                name="job_notification_error_only_when_email_enabled",
            ),
        ),
    ]
