# Generated by Django 6.0.3 on 2026-05-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_merge_20260509_2206"),
        ("monsters", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="monsterimagegenerationjob",
            name="job_queued_has_no_timestamps",
        ),
        migrations.RemoveConstraint(
            model_name="monsterimagegenerationjob",
            name="job_running_has_started_at_only",
        ),
        migrations.RemoveConstraint(
            model_name="monsterimagegenerationjob",
            name="job_succeeded_has_both_timestamps",
        ),
        migrations.RemoveConstraint(
            model_name="monsterimagegenerationjob",
            name="job_failed_blocked_have_both_timestamps",
        ),
        migrations.AddConstraint(
            model_name="monsterimagegenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "queued"),
                    models.Q(
                        ("started_at__isnull", False),
                        ("finished_at__isnull", False),
                        _connector="OR",
                    ),
                    _negated=True,
                ),
                name="job_queued_no_timestamps",
            ),
        ),
        migrations.AddConstraint(
            model_name="monsterimagegenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "running"),
                    models.Q(
                        ("started_at__isnull", True),
                        ("finished_at__isnull", False),
                        _connector="OR",
                    ),
                    _negated=True,
                ),
                name="job_running_started_not_finished",
            ),
        ),
        migrations.AddConstraint(
            model_name="monsterimagegenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "succeeded"),
                    models.Q(
                        ("started_at__isnull", True),
                        ("finished_at__isnull", True),
                        _connector="OR",
                    ),
                    _negated=True,
                ),
                name="job_succeeded_both_timestamps",
            ),
        ),
        migrations.AddConstraint(
            model_name="monsterimagegenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "failed"), ("finished_at__isnull", True), _negated=True
                ),
                name="job_failed_has_finished_at",
            ),
        ),
        migrations.AddConstraint(
            model_name="monsterimagegenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "blocked"),
                    models.Q(
                        ("started_at__isnull", True),
                        ("finished_at__isnull", True),
                        _connector="OR",
                    ),
                    _negated=True,
                ),
                name="job_blocked_both_timestamps",
            ),
        ),
        migrations.AddConstraint(
            model_name="monsterimagegenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["queued", "running"]),
                    models.Q(("error_code", ""), _negated=True),
                    _negated=True,
                ),
                name="job_active_no_error",
            ),
        ),
        migrations.AddConstraint(
            model_name="monsterimagegenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "succeeded"),
                    models.Q(("error_code", ""), _negated=True),
                    _negated=True,
                ),
                name="job_succeeded_no_error",
            ),
        ),
        migrations.AddConstraint(
            model_name="monsterimagegenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "failed"), ("error_code", ""), _negated=True
                ),
                name="job_failed_has_error_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="monsterimagegenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "blocked"), ("error_code", ""), _negated=True
                ),
                name="job_blocked_has_error_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="monsterimagegenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["queued", "running"]),
                    ("image_id__isnull", False),
                    _negated=True,
                ),
                name="job_active_no_image",
            ),
        ),
        migrations.AddConstraint(
            model_name="monsterimagegenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "succeeded"), ("image_id__isnull", True), _negated=True
                ),
                name="job_succeeded_has_image",
            ),
        ),
        migrations.AddConstraint(
            model_name="monsterimagegenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["failed", "blocked"]),
                    ("image_id__isnull", False),
                    _negated=True,
                ),
                name="job_terminal_error_no_image",
            ),
        ),
        migrations.AddConstraint(
            model_name="monsterimagegenerationjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("should_email_when_done", False),
                    ("notified_at__isnull", False),
                    _negated=True,
                ),
                name="job_notified_at_only_when_email_enabled",
            ),
        ),
    ]
