# Generated by Django 6.0.3 on 2026-05-12 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monsters", "0002_add_comprehensive_job_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monsterimagegenerationjob",
            name="image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generation_job",
                to="monsters.monsterimage",
            ),
        ),
        migrations.AlterField(
            model_name="monsterimagegenerationjob",
            name="monster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image_generation_jobs",
                to="monsters.monster",
            ),
        ),
    ]
