# Generated by Django 6.0.3 on 2026-05-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monsters", "0003_alter_monsterimagegenerationjob_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monster",
            name="flavor_text",
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name="monsterimage",
            name="public_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
