# Generated by Django 6.0.3 on 2026-05-20 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monsters", "0004_extend_public_image_url_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monsterimagegenerationjob",
            name="image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generation_job",
                to="monsters.monsterimage",
            ),
        ),
    ]
