# Generated by Django 6.0.3 on 2026-05-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monsters", "0005_image_gen_job_set_null_on_image_delete"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="monsterimagegenerationjob",
            name="job_succeeded_has_image",
        ),
    ]
