"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import sentry_sdk
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

IS_RENDER = os.environ.get("RENDER") == "true"

# Sentry defaults environment to "production" unless explicitly set.
SENTRY_ENVIRONMENT = os.environ.get(
    "SENTRY_ENVIRONMENT",
    os.environ.get("DJANGO_ENV", "production" if IS_RENDER else "development"),
)


def traces_sampler(sampling_context):
    """
    Ensures that pings to /health are ignored in Sentry logs.
    This is because Render pings /health every five seconds which is annoying to log
    """
    wsgi_environ = sampling_context.get("wsgi_environ", {})
    # Ensure Sentry ignores /health pings in logs. Both paths are registered.
    if wsgi_environ.get("PATH_INFO") in ("/health", "/health/"):
        return 0  # drop it
    return 1.0  # your normal sample rate


# Sentry error monitoring and logging
sentry_sdk.init(
    dsn=os.environ.get(
        "SENTRY_DSN",
        "https://8f3b1649ff89f8f8621e60e08eb4b2b2@o4511128491261952.ingest.us.sentry.io/4511289614336000",
    ),
    environment=SENTRY_ENVIRONMENT,
    enable_logs=True,
    # Add data like request headers and IP for users,
    # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
    send_default_pii=True,
    traces_sampler=traces_sampler,
)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "dev-only-insecure-secret-key",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = (
    os.environ.get(
        "DJANGO_DEBUG",
        "False" if IS_RENDER else "True",
    ).lower()
    == "true"
)

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

if render_hostname := os.environ.get("RENDER_EXTERNAL_HOSTNAME"):
    ALLOWED_HOSTS.append(render_hostname)

if extra_hosts := os.environ.get("DJANGO_ALLOWED_HOSTS"):
    ALLOWED_HOSTS.extend(
        host.strip() for host in extra_hosts.split(",") if host.strip()
    )


def csv_env(name: str, default: str = "") -> list[str]:
    return [
        value.strip()
        for value in os.environ.get(name, default).split(",")
        if value.strip()
    ]


CSRF_TRUSTED_ORIGINS = csv_env("CSRF_TRUSTED_ORIGINS")

if render_hostname := os.environ.get("RENDER_EXTERNAL_HOSTNAME"):
    CSRF_TRUSTED_ORIGINS.append(f"https://{render_hostname}")


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "apps.common.apps.CommonConfig",
    "apps.accounts.apps.AccountsConfig",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


CORS_ALLOWED_ORIGINS = csv_env(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000",
)


ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        # SQLite fallback for local dev without DATABASE_URL set.
        # In practice, always set DATABASE_URL in .env for real work.
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,  # Keep DB connections alive for reuse across requests
        conn_health_checks=True,  # Check connection health before reuse (recommended with conn_max_age)
        ssl_require=not DEBUG,  # Require SSL in production; skip for local SQLite fallback
    )
}

# Supabase Auth — used for JWT verification on protected API routes.
# SUPABASE_URL is the project URL: https://<project-ref>.supabase.co
SUPABASE_URL = os.environ.get("SUPABASE_URL", "")
# Tokens issued by Supabase always have audience="authenticated" for logged-in users.
SUPABASE_AUTH_AUDIENCE = os.environ.get("SUPABASE_AUTH_AUDIENCE", "authenticated")
# Derived from SUPABASE_URL — do not override these unless you know what you are doing.
SUPABASE_JWT_ISSUER = f"{SUPABASE_URL}/auth/v1" if SUPABASE_URL else ""
SUPABASE_JWKS_URL = (
    f"{SUPABASE_URL}/auth/v1/.well-known/jwks.json" if SUPABASE_URL else ""
)
# Signing algorithm for JWT verification. Must match the algorithm shown in
# Supabase Dashboard → Authentication → JWT Signing Keys.
# ES256 (Elliptic Curve, recommended) or RS256 (RSA). New projects default to ES256.
SUPABASE_JWT_ALGORITHM = os.environ.get("SUPABASE_JWT_ALGORITHM", "ES256")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Serializer stuff
SPECTACULAR_SETTINGS = {
    "TITLE": "Monster Masher API",
    "DESCRIPTION": "Django REST API for Monster Masher.",
    "VERSION": "0.1.0",
    # Prevents /api/schema/ and /api/docs/ from listing themselves in the schema.
    "SERVE_INCLUDE_SCHEMA": False,
}

# Django REST Framework
REST_FRAMEWORK = {
    # Phase 4 of our build plan will replace these with Supabase JWT auth.
    # AllowAny here is intentional, not accidental — no protected endpoints exist yet. Will be changed later.
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    # Only render JSON in production. Browsable HTML API is for local dev only.
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "EXCEPTION_HANDLER": "apps.common.exceptions.custom_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

if DEBUG:
    REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] = list(
        REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"]
    ) + [
        "rest_framework.renderers.BrowsableAPIRenderer",
    ]

# Use SQLite in-memory for tests so they are fast, isolated, and never hit an
# external service (Supabase or its PgBouncer pooler).
import sys  # noqa: E402

if "test" in sys.argv:
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ":memory:",
    }
