import uuid

from django.test import TestCase

from apps.accounts.models import UserProfile


class UserProfileModelTests(TestCase):
    def test_creates_with_supabase_user_id(self):
        profile = UserProfile.objects.create(
            supabase_user_id=uuid.uuid4(),
            email="test@example.com",
        )
        self.assertIsNotNone(profile.id)
        self.assertEqual(profile.email, "test@example.com")

    def test_supabase_user_id_is_unique(self):
        from django.db import IntegrityError, transaction

        uid = uuid.uuid4()
        UserProfile.objects.create(supabase_user_id=uid)
        with self.assertRaises(IntegrityError):
            with transaction.atomic():
                UserProfile.objects.create(supabase_user_id=uid)

    def test_is_authenticated_returns_true(self):
        profile = UserProfile(supabase_user_id=uuid.uuid4())
        self.assertTrue(profile.is_authenticated)

    def test_str_returns_email_when_set(self):
        profile = UserProfile(supabase_user_id=uuid.uuid4(), email="a@b.com")
        self.assertEqual(str(profile), "a@b.com")

    def test_str_returns_supabase_id_when_email_blank(self):
        uid = uuid.uuid4()
        profile = UserProfile(supabase_user_id=uid)
        self.assertEqual(str(profile), str(uid))

    def test_requires_email(self):
        from django.core.exceptions import ValidationError

        profile = UserProfile(supabase_user_id=uuid.uuid4())
        with self.assertRaises(ValidationError):
            profile.full_clean()

    def test_has_expected_autogenerated_fields(self):
        profile = UserProfile.objects.create(
            supabase_user_id=uuid.uuid4(),
            email="bob@example.com",
        )
        self.assertIsNotNone(profile.created_at)
        self.assertIsNotNone(profile.updated_at)

    def test_updated_at_changes_on_save(self):
        import time

        profile = UserProfile.objects.create(
            supabase_user_id=uuid.uuid4(),
            email="test@example.com",
        )
        original_updated_at = profile.updated_at
        time.sleep(0.01)
        profile.email = "newemail@example.com"
        profile.save()
        self.assertGreater(profile.updated_at, original_updated_at)

    def test_id_is_uuid(self):
        profile = UserProfile.objects.create(
            supabase_user_id=uuid.uuid4(),
            email="test@example.com",
        )
        self.assertIsInstance(profile.id, uuid.UUID)
