# Generated by Django 6.0.3 on 2026-05-09 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userprofile_display_name"),
        ("accounts", "0002_alter_userprofile_email"),
    ]

    operations = []
