/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user profile
         * @description GET /api/me/ — return the authenticated user's profile (no monsters).
         *
         *     Lightweight profile-only endpoint. Use POST /api/me/bootstrap/ when the
         *     full profile + monsters payload is needed (e.g. on initial page load).
         */
        get: operations["api_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/bootstrap/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create or fetch UserProfile (with monsters) for the current Supabase user
         * @description Idempotent. Returns profile fields plus the user's saved monsters, each with their most recent MonsterImage (or null). The authentication class already creates the profile on first verified request, but this endpoint gives the frontend a clean 'finish login' hook to call explicitly after auth confirm.
         */
        post: operations["api_me_bootstrap_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/image-gens-remaining/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get remaining image generations for today
         * @description GET /api/me/image-gens-remaining/
         *
         *     Returns how many image generations the authenticated user has left today.
         *
         *     Counts all MonsterImageGenerationJob records created in the last 24 hours
         *     for this user (regardless of outcome — succeeded, failed, or blocked all
         *     consume quota).
         *
         *     TODO (stretch): Only count jobs where generation_mode == "real" so that
         *     fake/dev generations do not tick down the daily limit. This would allow
         *     developers to test the UI without burning tokens.
         */
        get: operations["api_me_image_gens_remaining_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monsters/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List current user's monsters
         * @description GET  /api/monsters/   — list the authenticated user's monsters.
         *     POST /api/monsters/   — create a monster owned by the authenticated user.
         */
        get: operations["api_monsters_list"];
        put?: never;
        /**
         * Create a monster
         * @description GET  /api/monsters/   — list the authenticated user's monsters.
         *     POST /api/monsters/   — create a monster owned by the authenticated user.
         */
        post: operations["api_monsters_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monsters/{monster_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a monster
         * @description GET    /api/monsters/{monster_id}/ — retrieve a monster.
         *     PATCH  /api/monsters/{monster_id}/ — partial-update a monster.
         *     DELETE /api/monsters/{monster_id}/ — delete a monster.
         *
         *     Returns 404 (not 403) when the monster does not exist or belongs to
         *     another user.
         */
        get: operations["api_monsters_retrieve"];
        put?: never;
        post?: never;
        /**
         * Delete a monster
         * @description GET    /api/monsters/{monster_id}/ — retrieve a monster.
         *     PATCH  /api/monsters/{monster_id}/ — partial-update a monster.
         *     DELETE /api/monsters/{monster_id}/ — delete a monster.
         *
         *     Returns 404 (not 403) when the monster does not exist or belongs to
         *     another user.
         */
        delete: operations["api_monsters_destroy"];
        options?: never;
        head?: never;
        /**
         * Partial-update a monster
         * @description GET    /api/monsters/{monster_id}/ — retrieve a monster.
         *     PATCH  /api/monsters/{monster_id}/ — partial-update a monster.
         *     DELETE /api/monsters/{monster_id}/ — delete a monster.
         *
         *     Returns 404 (not 403) when the monster does not exist or belongs to
         *     another user.
         */
        patch: operations["api_monsters_partial_update"];
        trace?: never;
    };
    "/api/monsters/{monster_id}/generate-image/jobs/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an image generation job
         * @description POST /api/monsters/{monster_id}/generate-image/jobs/
         *
         *     Creates a generation job attached to the given monster. monster_id is
         *     always taken from the URL — never from the request body.
         */
        post: operations["api_monsters_generate_image_jobs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monsters/{monster_id}/generate-image/jobs/{job_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an image generation job
         * @description GET /api/monsters/{monster_id}/generate-image/jobs/{job_id}/
         *
         *     Returns 404 (not 403) when the job does not exist, belongs to another
         *     user, or is not attached to the given monster.
         */
        get: operations["api_monsters_generate_image_jobs_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monsters/{monster_id}/generate-image/jobs/{job_id}/notification/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Toggle email notification preference for a job
         * @description PATCH /api/monsters/{monster_id}/generate-image/jobs/{job_id}/notification/
         *
         *     Toggle email notification preference. Returns 400 if the job is already
         *     in a terminal state (succeeded, failed, or blocked) because the
         *     notification window has closed.
         */
        patch: operations["api_monsters_generate_image_jobs_notification_partial_update"];
        trace?: never;
    };
    "/api/monsters/{monster_id}/generate-image/mark-blocked/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark image generation job as blocked (content policy)
         * @description POST /api/monsters/{monster_id}/generate-image/mark-blocked/
         *
         *     Transitions a QUEUED or RUNNING job to BLOCKED. Called by the Next.js
         *     pipeline when the banned-terms guard or moderation provider rejects the prompt.
         *
         *     Body: { job_id, error_code, error_message }
         *     Returns: the updated MonsterImageGenerationJob.
         */
        post: operations["api_monsters_generate_image_mark_blocked_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monsters/{monster_id}/generate-image/mark-failed/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark image generation job as failed
         * @description POST /api/monsters/{monster_id}/generate-image/mark-failed/
         *
         *     Transitions a QUEUED or RUNNING job to FAILED. Called by the Next.js
         *     pipeline on provider or storage errors.
         *
         *     Body: { job_id, error_code, error_message }
         *     Returns: the updated MonsterImageGenerationJob.
         */
        post: operations["api_monsters_generate_image_mark_failed_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monsters/{monster_id}/generate-image/mark-running/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark image generation job as running
         * @description POST /api/monsters/{monster_id}/generate-image/mark-running/
         *
         *     Transitions a QUEUED job to RUNNING. Called by the Next.js pipeline
         *     after moderation passes and before image generation begins.
         *
         *     Body: { job_id }
         *     Returns: the updated MonsterImageGenerationJob.
         */
        post: operations["api_monsters_generate_image_mark_running_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monsters/{monster_id}/generate-image/mark-succeeded/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark image generation job as succeeded and create MonsterImage
         * @description POST /api/monsters/{monster_id}/generate-image/mark-succeeded/
         *
         *     Transitions a RUNNING job to SUCCEEDED and creates the MonsterImage record.
         *     Called by the Next.js pipeline after the image has been uploaded to storage.
         *
         *     Body: { job_id, monster_image_id, public_image_url, image_storage_path,
         *             provider, provider_model }
         *     Returns: the updated MonsterImageGenerationJob (including the linked image).
         */
        post: operations["api_monsters_generate_image_mark_succeeded_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/monsters/{monster_id}/image/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete the current image for a monster
         * @description DELETE /api/monsters/{monster_id}/image/
         *
         *     Deletes the current MonsterImage for a monster. The monster record itself
         *     is preserved. MonsterImageGenerationJob records linked to the deleted image
         *     are also preserved as historical records — they document that a generation
         *     attempt was made and are useful for admin visibility and rate-limit counting.
         *
         *     Design note: this endpoint is called by the Next.js generate-image route
         *     before retrying image generation for a monster that already has an image.
         *     Keeping old job records means the admin can see retry patterns, and the
         *     rate limiter correctly counts retries against the daily quota.
         *
         *     Returns 204 if the image was deleted, or 404 if the monster has no image.
         */
        delete: operations["api_monsters_image_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns ok when the server is running. Unauthenticated.
         */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `fake` - Fake
         *     * `real` - Real
         * @enum {string}
         */
        GenerationModeEnum: "fake" | "real";
        HealthResponse: {
            status: string;
        };
        /**
         * @description Nested generation_metadata sub-object on MonsterImageGenerationJob.
         *
         *     sanitized_prompt is intentionally excluded from the frontend-facing
         *     response (Step 2f decision). prompt_version and prompt_hash are safe
         *     identifiers useful for debugging/drift detection.
         */
        JobGenerationMetadata: {
            readonly prompt_version: string;
            readonly prompt_hash: string;
        };
        /**
         * @description Nested notify_when_done sub-object on MonsterImageGenerationJob.
         *
         *     notification_error is null when no notification error has occurred.
         *     When present, it carries only safe code/message — no internal details.
         */
        JobNotifyWhenDone: {
            readonly should_email_when_done: boolean;
            /** Format: date-time */
            readonly notified_at: string | null;
            /** @description Null when no notification error has occurred. Present only when email delivery failed. */
            readonly notification_error: {
                code: string;
                message: string;
            } | null;
        };
        /**
         * @description Nested provider_info sub-object on MonsterImageGenerationJob.
         *     Maps to provider, provider_model, provider_request_id on the model.
         */
        JobProviderInfo: {
            readonly provider: string;
            readonly provider_model: string;
            readonly provider_request_id: string;
        };
        /**
         * @description Nested timestamps sub-object on MonsterImageGenerationJob.
         *     Groups all lifecycle timestamps together.
         */
        JobTimestamps: {
            /** Format: date-time */
            readonly started_at: string | null;
            /** Format: date-time */
            readonly finished_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description POST body for mark-blocked.
         *
         *     Used for content policy violations (banned-terms guard, moderation provider).
         *     The job may be in QUEUED or RUNNING state when this is called.
         */
        MarkJobBlocked: {
            /** Format: uuid */
            job_id: string;
            error_code: string;
            error_message: string;
        };
        /**
         * @description POST body for mark-failed.
         *
         *     error_code is required; error_message is the safe user-facing description.
         */
        MarkJobFailed: {
            /** Format: uuid */
            job_id: string;
            error_code: string;
            error_message: string;
        };
        /**
         * @description POST body for mark-running.
         *
         *     Identifies the specific job to transition; the monster is in the URL.
         */
        MarkJobRunning: {
            /** Format: uuid */
            job_id: string;
        };
        /**
         * @description POST body for mark-succeeded.
         *
         *     Carries the image metadata that Django will use to create the MonsterImage
         *     record and link it to the job.
         */
        MarkJobSucceeded: {
            /** Format: uuid */
            job_id: string;
            /** Format: uuid */
            monster_image_id: string;
            /** Format: uri */
            public_image_url: string;
            image_storage_path: string;
            provider: string;
            provider_model: string;
        };
        /**
         * @description Read/response serializer for Monster.
         *
         *     Exposes traits as a nested object even though they are stored as flat
         *     columns on the model. source="*" passes the whole instance to the nested
         *     serializer so each trait field reads from the instance attribute directly.
         *
         *     image is the most recently created MonsterImage for this monster, or null
         *     if no image has been generated yet.
         */
        Monster: {
            /** Format: uuid */
            readonly id: string;
            display_name: string;
            readonly traits: components["schemas"]["MonsterTraits"];
            flavor_text?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly image: components["schemas"]["MonsterImage"] | null;
        };
        /**
         * @description POST request serializer for Monster.
         *
         *     Owner is always set from request context. Never accepted from client input.
         */
        MonsterCreate: {
            display_name: string;
            traits: components["schemas"]["MonsterTraits"];
            /** @default  */
            flavor_text: string;
        };
        /**
         * @description Read/response serializer for MonsterImage.
         *
         *     Exposes safe image display metadata. image_storage_path is intentionally
         *     included per explicit decision (see Step 2e).
         *     No image bytes, no base64, no raw provider response.
         */
        MonsterImage: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uri */
            readonly public_image_url: string | null;
            /** @description Object storage path used for cleanup. Intentionally exposed per Step 2e decision. */
            readonly image_storage_path: string;
            readonly provider: string;
            readonly provider_model: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description Read/response serializer for MonsterImageGenerationJob.
         *
         *     Flat model columns are exposed as nested sub-objects to match
         *     the groupings annotated in models.py:
         *
         *         provider_info     — provider, provider_model, provider_request_id
         *         generation_metadata — prompt_version, prompt_hash
         *                               (sanitized_prompt excluded per Step 2f)
         *         notify_when_done  — should_email_when_done, notified_at, notification_error
         *         error_info        — null unless job failed/blocked
         *         timestamps        — started_at, finished_at, created_at, updated_at
         *         image             — nested MonsterImage when succeeded, else null
         */
        MonsterImageGenerationJob: {
            /** Format: uuid */
            readonly id: string;
            /**
             * Format: uuid
             * @description UUID of the associated Monster, or null if the job failed before a Monster was created.
             */
            readonly monster: string | null;
            /**
             * @description Lifecycle state: queued → running → succeeded | failed | blocked.
             *
             *     * `queued` - Queued
             *     * `running` - Running
             *     * `succeeded` - Succeeded
             *     * `failed` - Failed
             *     * `blocked` - Blocked
             */
            readonly status: components["schemas"]["StatusEnum"];
            /**
             * @description fake uses fixture images (no provider cost). real calls the configured image provider.
             *
             *     * `fake` - Fake
             *     * `real` - Real
             */
            readonly generation_mode: components["schemas"]["GenerationModeEnum"];
            readonly provider_info: components["schemas"]["JobProviderInfo"];
            readonly generation_metadata: components["schemas"]["JobGenerationMetadata"];
            readonly notify_when_done: components["schemas"]["JobNotifyWhenDone"];
            /** @description Null for queued/running/succeeded jobs. Present with code and message when status is failed or blocked. */
            readonly error_info: {
                code: string;
                message: string;
            } | null;
            readonly image: components["schemas"]["MonsterImage"] | null;
            readonly timestamps: components["schemas"]["JobTimestamps"];
        };
        /**
         * @description POST request serializer for MonsterImageGenerationJob.
         *
         *     Owner is always set from request context. monster_id comes from the URL
         *     kwargs, not the request body. Status, provider, prompt, and all other
         *     internal fields are never accepted from client input.
         */
        MonsterImageGenerationJobCreate: {
            /** @default false */
            should_email_when_done: boolean;
        };
        /**
         * @description Nested traits sub-object. Maps to flat columns on Monster.
         *
         *     CharField defaults (trim_whitespace=True, allow_blank=False) enforce
         *     trimmed, non-blank values on all four fields.
         */
        MonsterTraits: {
            /** @description Free-text element descriptor. Not an enum — frontend may suggest values but any text is accepted. */
            element: string;
            habitat: string;
            personality: string;
            color_palette: string;
        };
        /**
         * @description PATCH request serializer for the notification toggle endpoint.
         *
         *     Only allows setting should_email_when_done. Owner, status, and all
         *     other job fields are structurally impossible to change via this serializer.
         */
        PatchedMonsterImageGenerationJobNotificationUpdate: {
            should_email_when_done?: boolean;
        };
        /**
         * @description PATCH request serializer for Monster.
         *
         *     All fields are optional so any subset can be updated.
         *     If traits is provided, all four trait fields within it are required.
         *     Owner cannot be changed.
         */
        PatchedMonsterUpdate: {
            display_name?: string;
            traits?: components["schemas"]["MonsterTraits"];
            flavor_text?: string;
        };
        /**
         * @description * `queued` - Queued
         *     * `running` - Running
         *     * `succeeded` - Succeeded
         *     * `failed` - Failed
         *     * `blocked` - Blocked
         * @enum {string}
         */
        StatusEnum: "queued" | "running" | "succeeded" | "failed" | "blocked";
        UserProfile: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly supabase_user_id: string;
            /** Format: email */
            readonly email: string;
            readonly display_name: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description Extended UserProfile serializer that nests the user's saved monsters (with images).
         *
         *     Used by POST /api/me/bootstrap/ so the frontend can hydrate the full initial
         *     auth state — profile + monsters — in a single request.
         *
         *     The monsters list is ordered by creation date (newest first), matching the
         *     Monster model's default ordering.  Each monster's ``image`` field is the
         *     most recently created MonsterImage, or null if none exists yet.
         *
         *     This serializer is intentionally read-only; monster mutations go through the
         *     dedicated /api/monsters/* endpoints.
         */
        UserProfileWithMonsters: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly supabase_user_id: string;
            /** Format: email */
            readonly email: string;
            readonly display_name: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly monsters: components["schemas"]["Monster"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    api_me_bootstrap_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileWithMonsters"];
                };
            };
        };
    };
    api_me_image_gens_remaining_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description How many image generations the user can still trigger today. */
                        num_remaining: number;
                        /** @description The daily cap configured for this deployment. */
                        max_per_day: number;
                        /** @description Jobs created in the last 24 hours. */
                        used_today: number;
                    };
                };
            };
        };
    };
    api_monsters_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Monster"][];
                };
            };
        };
    };
    api_monsters_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MonsterCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["MonsterCreate"];
                "multipart/form-data": components["schemas"]["MonsterCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Monster"];
                };
            };
        };
    };
    api_monsters_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monster_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Monster"];
                };
            };
        };
    };
    api_monsters_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monster_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_monsters_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monster_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMonsterUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMonsterUpdate"];
                "multipart/form-data": components["schemas"]["PatchedMonsterUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Monster"];
                };
            };
        };
    };
    api_monsters_generate_image_jobs_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monster_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MonsterImageGenerationJobCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["MonsterImageGenerationJobCreate"];
                "multipart/form-data": components["schemas"]["MonsterImageGenerationJobCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonsterImageGenerationJob"];
                };
            };
        };
    };
    api_monsters_generate_image_jobs_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                monster_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonsterImageGenerationJob"];
                };
            };
        };
    };
    api_monsters_generate_image_jobs_notification_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                monster_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMonsterImageGenerationJobNotificationUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMonsterImageGenerationJobNotificationUpdate"];
                "multipart/form-data": components["schemas"]["PatchedMonsterImageGenerationJobNotificationUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonsterImageGenerationJob"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_monsters_generate_image_mark_blocked_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monster_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkJobBlocked"];
                "application/x-www-form-urlencoded": components["schemas"]["MarkJobBlocked"];
                "multipart/form-data": components["schemas"]["MarkJobBlocked"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonsterImageGenerationJob"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_monsters_generate_image_mark_failed_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monster_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkJobFailed"];
                "application/x-www-form-urlencoded": components["schemas"]["MarkJobFailed"];
                "multipart/form-data": components["schemas"]["MarkJobFailed"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonsterImageGenerationJob"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_monsters_generate_image_mark_running_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monster_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkJobRunning"];
                "application/x-www-form-urlencoded": components["schemas"]["MarkJobRunning"];
                "multipart/form-data": components["schemas"]["MarkJobRunning"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonsterImageGenerationJob"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_monsters_generate_image_mark_succeeded_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monster_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkJobSucceeded"];
                "application/x-www-form-urlencoded": components["schemas"]["MarkJobSucceeded"];
                "multipart/form-data": components["schemas"]["MarkJobSucceeded"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonsterImageGenerationJob"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_monsters_image_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                monster_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
